### ISSUE TITLE
Standard and File Message for MessageEnvelope

### ISSUE THREAD

**Issue by hellenfc** [pubnub/react-chat-components#12]
Currently I'm trying to create a custom `bubbleRenderer` for `MessageList` . This are the properties I'm getting, when I try to access message it uses `MessageEnvelope` as its Type and the message type is always handled as `FileMessage` and not `StandardMessage`, even when it is a `StandardMessage`. What can I do for it to handle it as Standard Message or is there a bug?

Properties:
![Screen Shot 2021-09-01 at 5 16 23 PM](https://user-images.githubusercontent.com/12178847/131757535-8374d0ae-4dd3-4e7b-b97e-1b4b25953d9a.png)

Message as `FileMessage`  when it really is `StandardMessage`
![Screen Shot 2021-09-01 at 5 18 27 PM](https://user-images.githubusercontent.com/12178847/131757670-f3aeb86f-eb83-4f6e-a189-ede63b4b31ad.png)

**Comment by hellenfc** [comment]
Found solution, needed to cast message.

**Comment by jpjpjp** [comment]
@hellenfc thank you for sharing the solution and closing the issue!
