### ISSUE TITLE
Support react-native

### ISSUE THREAD

**Issue by kelvin-dev** [pubnub/react-chat-components#25]
Dear team, we love your work, please help support porting this sample into react-native project,
Cheers,

**Comment by smacky2301** [comment]
Hey kelvin-dev! Thanks for reaching out to us. This tutorial may be useful for you: https://kris101.medium.com/building-a-react-native-chat-app-part-one-basic-messaging-pubnub-18d6bd528d4f

**Comment by Salet** [comment]
Hi @kelvin-dev, thanks for your interest in our product. I'm happy to say that React Native is now supported via a dedicated [npm package](https://www.npmjs.com/package/@pubnub/react-native-chat-components). Please also check out [our docs ](https://www.pubnub.com/docs/chat/components/react-native)for information on how to start using it.
