### ISSUE TITLE
no user metadata in MessageList

### ISSUE THREAD

**Issue by abe-winter** [pubnub/react-chat-components#28]
## Overview

The MessageList component isn't rendering user meta information (see screenshot). I'm not sure it's even fetching it.

What it looks like on my system:
![pubnub-sample-messagelist](https://user-images.githubusercontent.com/7256523/155895381-a32b5606-0aaf-453a-928f-90427590d7e1.png)

per docs [here](https://pubnub.github.io/react-chat-components/docs/?path=/docs/introduction-about--page), it's supposed to look like this:
![image](https://user-images.githubusercontent.com/7256523/155896074-080f90ec-88ca-4e4f-97ec-895d51496b45.png)

I'm calling `set_uuid_metadata` on the server for this UUID.

I have `logVerbosity: true` in the PubNub client object, and I'm not seeing fetches of the member list. The SDK is making API calls to /presence (2x), /history-with-actions (2x), and /subscribe (5x).

## Code readthrough

From browsing code, it looks like the default message renderer calls getUser:
https://github.com/pubnub/react-chat-components/blob/0bfd2221a3ea16c4b3d51d8ced1ae3b5e421bf1e/lib/src/message-list/message-list.tsx#L152-L153

which searches the users collection
https://github.com/pubnub/react-chat-components/blob/0bfd2221a3ea16c4b3d51d8ced1ae3b5e421bf1e/lib/src/message-list/message-list.tsx#L81

which is set from UsersMetaAtom, which doesn't have an async getter
https://github.com/pubnub/react-chat-components/blob/0bfd2221a3ea16c4b3d51d8ced1ae3b5e421bf1e/lib/src/state-atoms.ts#L9

## Possible explanation -- typescript

I'm not using typescript in my project. Does react-chat-components require typescript?

I'm not familiar with jotai, so I may be misreading, or missing some behavior provided by typescript inheritance. The UUIDMetadataObject which react-chat-components uses here:
https://github.com/pubnub/react-chat-components/blob/0bfd2221a3ea16c4b3d51d8ced1ae3b5e421bf1e/lib/src/state-atoms.ts#L1

Isn't defined anywhere in the pubnub/javascript repo (at current 5.0 or at the v4.29 referenced by react-chat-components), but it *is* defined in the DefinitelyTyped for pubnub, here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pubnub/index.d.ts#L1414

## Possible confounding factor -- access manager

I'm using the access manager, and I think the current authKey has access to the Channel but not all user UUIDs globally

## Possible confounding factor -- only using MessageList

I'm not using the other chat components (MemberList, ChannelList). If MemberList is responsible for fetching the UUID metadata, that could explain why my MessageList doesn't have it.

## Thanks

Sorry for long writeup, thanks for providing this library

**Comment by Salet** [comment]
Hi @abe-winter, thanks for reaching out and sorry for my late response.

The recent versions of PubNub Chat Components for React are indifferent to the source of metadata for your users, channels and memberships. It means that you, as the developer, are responsible for providing the data into the components. This is documented in more detail [here](https://pubnub.github.io/react-chat-components/docs/?path=/docs/introduction-metadata--page).

In case you are using PubNub Objects API to store your data by using `set_uuid_metadata`, then what you can do is call `useUsers` [custom hook](https://pubnub.github.io/react-chat-components/docs/?path=/docs/custom-hooks-useusers--page) to fetch your users and pass them directly to the Chat Provider's `users` prop.

Please let me know if that fixes your issue.

**Comment by abe-winter** [comment]
ah thank you, I'll try that + update here

**Comment by McRipper** [comment]
Any news on the issue? I'm having the same problem

**Comment by Salet** [comment]
Please consult [this documentation page](https://pubnub.github.io/react-chat-components/docs/?path=/docs/code-examples-user-metadata--page) for code examples on how to pass user data into the components.
