### ISSUE TITLE
emojiPicker doesn't work in <MessageInput /> Component

### ISSUE THREAD

**Issue by yash-sharma01** [pubnub/react-chat-components#46]
```
import { Chat, MessageInput, MessageList } from "@pubnub/react-chat-components";
import { Picker } from "emoji-mart";
import PubNub from "pubnub";
import { PubNubProvider } from "pubnub-react";

const pubnub = new PubNub({
	publishKey: PUBLISH_KEY,
	subscribeKey: SUBSCRIBE_KEY,
	uuid: "myFirstUser",
});
const currentChannel = "Default";
const theme = "light";

export const PubNubChat = () => {
	const onError = (error) => {
		console.log(error);
	};
	return (
		<PubNubProvider client={pubnub}>
			<Chat {...{ currentChannel, theme, onError }}>
				<MessageList />
				<MessageInput
					typingIndicator
					emojiPicker={<Picker />}
				/>
			</Chat>
		</PubNubProvider>
	);
};
```
When starting the development server, the below component is rendered.
![image](https://user-images.githubusercontent.com/64589701/170365308-55ba3366-eb56-4760-806d-77e8be40d18a.png)

When the emoji icon is clicked, it throws the following error
 ```
 TypeError: Class constructor $724e43cd4d4265a7$export$2e2bcd8739ae039 cannot be invoked without 'new'
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
    at recoverFromConcurrentError (react-dom.development.js:25806:1)
    at performSyncWorkOnRoot (react-dom.development.js:26052:1)
    at flushSyncCallbacks (react-dom.development.js:12009:1)
 ```
 here is the console error
 
![image](https://user-images.githubusercontent.com/64589701/170365747-83a96f28-c202-491d-bfee-852cbd017053.png)

**Comment by lifeinafolder** [comment]
As per the documentation [here](https://pubnub.github.io/react-chat-components/docs/?path=/docs/introduction-emoji-pickers--page), you have to `import` the package like this:

```
import { Picker } from "emoji-mart";
import "emoji-mart/css/emoji-mart.css";
```

but even when I do that, I get the following error:

![Screen Shot 2022-08-16 at 4 37 07 PM](https://user-images.githubusercontent.com/91226/185003161-7e5f13b4-9a86-40bf-938e-5a9341e30a38.png)

Looks like an issue with CSS bundling of dependencies.

**Comment by Salet** [comment]
The documentation was showing usage with emoji-mart v3 and it looks like the library has been significantly changed in version 5.  Please make sure you are using v0.13.0 of the React Chat Components and consult the updated [documentation page](https://pubnub.github.io/react-chat-components/docs/?path=/docs/introduction-emoji-pickers--page) to fix this error.
