### ISSUE TITLE
Forks and build process

### ISSUE THREAD

**Issue by itdsntwork** [pubnub/react-chat-components#5]
Hey. I am trying to use a forked repo in order to enhance this package but installing by running eg `yarn add itdsntwork/react-chat-components` does not have the same output in node_modules as by adding the main package. Do you have a custom procedure for builds? Can you add info on how to use forked repos from this repo?

**Comment by Salet** [comment]
@itdsntwork this project is a monorepository and currently uses the Workspaces functionality of NPM 7. It hasn't been tested with yarn. Other than that the build process is rather standard, the components package is built with Rollup by running `npm run build` from inside the lib subfolder. Please let us know if it resolves the problem or not.
