### ISSUE TITLE
[Bug] layout issue of message-input

### ISSUE THREAD

**Issue by retsohuang** [pubnub/react-chat-components#62]
The text will be cut out after picking files on small screens 

![SCR-20220921-lj9](https://user-images.githubusercontent.com/785920/191443333-6d2304ae-4c34-476c-8e29-40f1f06d5aa7.png)

I think it should call `autoSize` after [this line](https://github.com/pubnub/react-chat-components/blob/da3a81b5cecc996588af37debc4f48cb027699ef/lib/src/message-input/message-input.tsx#L213) in MessageInput component?

**Comment by Salet** [comment]
Hi @retsohuang, thanks for reaching out. The issue has been fixed in [version 0.16.0](https://github.com/pubnub/react-chat-components/releases) of the components library.
